#!/usr/bin/env bash

# installs go first
wget https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
rm -rf /usr/local/go
tar -xzf go1.24.0.linux-amd64.tar.gz
mv go /usr/local
rm go1.24.0.linux-amd64.tar.gz

# install asdf
go install github.com/asdf-vm/asdf/cmd/asdf@v0.16.0
