#!/usr/bin/env bash

# installs go first
curl https://dl.google.com/go/go1.25.10.linux-amd64.tar.gz --output go_folder.tar.gz
rm -rf /usr/local/go
tar -xzf go_folder.tar.gz
mv go /usr/local
rm -f go_folder.tar.gz

# install asdf
/usr/local/go/bin/go install github.com/asdf-vm/asdf/cmd/asdf@latest
