#!/usr/bin/bash

cd /tmp

# Google chorme
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Chromium
sudo apt install chromium
