#!/usr/bin/env bash

asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs latest
asdf install nodejs 20.12.0
asdf install nodejs 16.20.0
asdf install nodejs 14.18.0

asdf set --home nodejs 20.12.0
