#!/usr/bin/env bash

sudo apt update -y && sudo apt upgrade -y

sudo apt install git curl vim fzf fd-find bat ripgrep git-delta pavucontrol xclip jq tldr-py flameshot python3-pip arandr snapd lxappearance feh compton rofi -y
